---
name: "MeshMeshGo Server"
version: "1.3.5"
slug: "meshmeshgo-addon"
description: "The MeshMeshGo Server"

arch:
  - aarch64
  - amd64

url: https://github.com/EspMeshMesh/meshmeshgo
image: ghcr.io/espmeshmesh/{arch}-meshmeshgo-addon
panel_icon: mdi:access-point-network
homeassistant: 2025.9.0

options:
  SerialPortName: ""
  SerialPortBaudRate: 460800
  WantHelp: false
  esp8266: false
  VerboseLevel: 0
  RestBindAddress: ":4000"
  BindAddress: "dynamic"
  BindPort: 6053
  BasePortOffset: 20000
  SizeOfPortsPool: 10000

schema:
  SerialPortName: device(subsystem=tty)
  SerialPortBaudRate: int?
  WantHelp: bool?
  esp8266: bool?
  VerboseLevel: int?
  TargetNode: int?
  DebugNodeAddr": int?
  RestBindAddress: str?
  RpcBindAddress: str?
  BindAddress: str?
  BindPort: int?
  BasePortOffset: int?
  SizeOfPortsPool: int?

ports:
  4040/tcp: 4040

init: false
startup: "services"

host_network: true
usb: true
uart: true
ingress: true
